server:
  port: 8087
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/movie_chart
    username: postgres
    password: pwd
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect